Windows - R-3.2: fixed installation on i386 (requires 4.9.2 toolchain) and x64 (disabled with no error)

diff --git a/configure-win b/configure-win
--- a/configure-win
+++ b/configure-win
@@ -19,7 +19,6 @@ if test -z "${R_HOME}"; then
 fi
 
 # load m4 Windows macros
-RSCRIPT=${R_HOME}/bin${R_ARCH_BIN}/Rscript.exe
 . exec/m4.win
 AC_INIT RcppOctave 0.18
 
@@ -32,15 +31,23 @@ fi
 
 ## Path to R binaries
 AC_PATH_PROG R_BIN R "" "${R_HOME}/bin${R_ARCH_BIN}"
-AC_PATH_PROG RSCRIPT_BIN Rscript "" "${R_HOME}/bin${R_ARCH_BIN}"
-AC_MSG_CHECKING "Rscript version"
-echo -n `"${RSCRIPT}" --version`
-AC_MSG_CHECKING "R platform"
-R_OS=`"${RSCRIPT}" -e "cat(R.version[['platform']])"`
-AC_MSG_RESULT ${R_OS}
+AC_PATH_PROG RSCRIPT Rscript "" "${R_HOME}/bin${R_ARCH_BIN}"
+#
 
-# init variable for possible changes to PATH
-PATH_EXPORT="# not used on ${R_OS}"
+RSCRIPT_ARG=''
+if test -n "${RSCRIPT_ARG}"; then
+	RSCRIPT="${RSCRIPT} ${RSCRIPT_ARG}"
+	RSCRIPT_ARG=" ${RSCRIPT_ARG}"
+	AC_MSG_NOTICE "Using Rscript command: ${RSCRIPT}"
+fi
+AC_SUBST RSCRIPT_ARG 
+#
+
+AC_MSG_CHECKING "R version"
+echo `${RSCRIPT} -e "cat(R.version[['version.string']])"`
+AC_MSG_CHECKING "R platform"
+R_OS=`${RSCRIPT} -e "cat(R.version[['platform']])"`
+AC_MSG_RESULT ${R_OS}
 
 # get compiler and compilation flags from R
 if test -n "${R_HOME}"; then
@@ -70,38 +77,13 @@ if test -n "${R_HOME}"; then
   AC_MSG_RESULT ${CXXLAGS}
 fi
 
-# check path to Rtools
-AC_PATH_RTOOLS "${R_CC_COMPILER}"
 
 echo "Checking system PATH..."
 AC_SYS_PATH
 
 # check R is a shared library
-R_LDFLAGS=`"${R_BIN}" CMD config --ldflags 2>/dev/null`
-R_CPPFLAGS=`"${R_BIN}" CMD config --cppflags 2>/dev/null`
-
-AC_MSG_NOTICE "Original R_LDFLAGS: ${R_LDFLAGS}"
-AC_MSG_NOTICE "Original R_CPPFLAGS: ${R_CPPFLAGS}"
-
-has_R_shlib=no
-if test -n "$R_LDFLAGS"; then
-   has_R_shlib=yes
-fi
-
-AC_MSG_CHECKING "whether R is a shared library"
-if test "${has_R_shlib}" = "no"; then
-	AC_MSG_RESULT "no"
-	# add path to R headers 
-	R_CPPFLAGS="-I'${R_INCLUDE_DIR}' -I'${R_INCLUDE_DIR}${R_ARCH}'"
-else
-   AC_MSG_RESULT "yes"
-fi
-
-
-
-
-AC_MSG_NOTICE "Using mkoctfile with R_LDFLAGS: ${R_LDFLAGS}"
-AC_MSG_NOTICE "Using mkoctfile with R_CPPFLAGS: ${R_CPPFLAGS}"
+R_LDFLAGS="\`\${R_BIN} CMD config --ldflags 2>/dev/null\`"
+R_CPPFLAGS="\`\${R_BIN} CMD config --cppflags 2>/dev/null\`"
 
 # pass R flags down to makefile in modules/
 AC_SUBST R_CPPFLAGS
@@ -144,38 +126,66 @@ if test "${OCTAVE_CONFIG}" != ""; then
 	if [ "x${OCT_CC_SPECS}" != "x${CC_SPECS}" ]; then
 		AC_MSG_RESULT "no [${OCT_CC_SPECS} vs ${CC_SPECS}]"
 		
-		if [ -z "${RTOOLS_PATH}" ]; then
-		echo "RcppOctave configuration error:
-			Default R compiler must be located within Rtools installation directory.
-			-> Check that Rtools bin/ sub-directory appears at the beginning of Windows PATH, and, in particular, _before_ Octave binary path.
-			"
-		exit 1
-		fi	
-
-		AC_CC_COMPATIBLE CC_BIN_BASE "${OCTAVE_CC}" "${RTOOLS_PATH}"
-		PATH_EXPORT="export PATH=${CC_BIN_BASE}:${PATH}"
-		AC_MSG_NOTICE "pre-pending '${CC_BIN_BASE}' to PATH"
+		if [ "x${RTOOLS_COMPILER_NO_LOOKUP}" = "" ]; then
+			# check path to Rtools
+			AC_PATH_RTOOLS "${R_CC_COMPILER}"
+			if [ -z "${RTOOLS_PATH}" ]; then
+			echo "RcppOctave configuration error:
+  Default R compiler must be located within Rtools installation directory.
+  -> Check that Rtools bin/ sub-directory appears at the beginning of Windows PATH, and, in particular, _before_ Octave binary path.
+"
+			exit 1
+			fi	
+	
+			AC_CC_COMPATIBLE CC_BIN_BASE "${OCTAVE_CC}" "${RTOOLS_PATH}"
+			SYSTEM_SPEC="ifneq \"\$(WIN)\" \"64\"\n  export PATH:=${CC_BIN_BASE}:\$(PATH)\nelse\n  OCT_LDFLAGS=\n  OCT_CPPFLAGS=\nendif"
+			AC_MSG_NOTICE "pre-pending '${CC_BIN_BASE}' to PATH"
+		else
+			echo "RcppOctave configuration error:
+  Rtools gcc version (${CC_SPECS}) is not compatible with Octave's version (${OCT_CC_SPECS}) 
+  -> Check that Rtools Windows native toolchain gcc-4.9.2 is located in a sub-directory of Rtools.
+  See https://rawgit.com/kevinushey/RToolsToolchainUpdate/master/mingwnotes.html
+"
+			exit 1
+		fi
 	else
 		AC_MSG_RESULT "yes"
 	fi
-		
-	# Include directory
-	AC_OCTAVE_MKCONFIG OCT_INCLUDEDIR OCTINCLUDEDIR "include directory"
 	
-	# Library directory
-	AC_OCTAVE_MKCONFIG OCT_LIBDIR OCTLIBDIR "lib directory"
-	
-	## System-specific variables (flags,target)
-	AC_SUBST PATH_EXPORT
 	AC_MSG_CHECKING "RcppOctave system-specific cpp flags"
 	PKG_CPPFLAGS_XTRA=-fmax-errors=10
-	AC_SUBST PKG_CPPFLAGS_XTRA
-    if test "${PKG_CPPFLAGS_XTRA}" = ""; then AC_MSG_RESULT "none"; else AC_MSG_RESULT "${PKG_CPPFLAGS_XTRA}"; fi
-
+	if test "${PKG_CPPFLAGS_XTRA}" = "" ; then AC_MSG_RESULT "none"; else AC_MSG_RESULT "${PKG_CPPFLAGS_XTRA}"; fi
+	SYSTEM_SPEC="${SYSTEM_SPEC}\nPKG_CPPFLAGS_XTRA=${PKG_CPPFLAGS_XTRA}"
+	
+	# Include directory
+	# AC_OCTAVE_MKCONFIG OCT_INCLUDEDIR OCTINCLUDEDIR "include directory"
+	
+	# Library directory
+	#	AC_OCTAVE_MKCONFIG OCT_LIBDIR OCTLIBDIR "lib directory"
+	
+	## pass on PATH modifications
+	AC_MSG_CHECKING "PATH changes"
+	if test "${PATH_EXPORT}" = ""; then
+		PATH_EXPORT="# none needed"
+		AC_MSG_RESULT "none"
+	else
+		AC_MSG_RESULT "${PATH_EXPORT}"
+		PATH_EXPORT="${PATH_EXPORT}\$(PATH_SEPARATOR)\$(PATH)"
+		PATH_EXPORT="export PATH:=${PATH_EXPORT}"
+	fi
+	AC_SUBST PATH_EXPORT
+	##
+	
+	## Octave module target
 	AC_MSG_CHECKING "Octave module make target"
-	OCT_TARGET=win-$(printf '%s' "${R_ARCH}" | sed -e 's@/@@g')
+	OCT_TARGET="win\${R_ARCH}"
 	AC_SUBST OCT_TARGET
 	AC_MSG_RESULT "${OCT_TARGET}"
+	##
+	
+	## System-specific statements (flags,target)
+	if test "${SYSTEM_SPEC}" = ""; then SYSTEM_SPEC="# none needed"; fi
+	AC_SUBST SYSTEM_SPEC
 	##
 
 	## mkoctfile command used to compile the modules
@@ -239,6 +249,7 @@ AC_SUBST OCT_MODULES_PATH
 # Configure libRrng
 #AC_CONFIG_SUBDIRS([src/modules])
 
+R_ARCH0=`echo "${R_ARCH}" | sed 's/\///'`
 AC_OUTPUT R/config-vars.R
-AC_OUTPUT src/Makevars
-AC_OUTPUT src/modules/Makefile
+AC_OUTPUT src-${R_ARCH0}/Makevars
+AC_OUTPUT src-${R_ARCH0}/modules/Makefile
